blank_issues_enabled: true
contact_links:
  - name: 💬 Question or help installing
    url: https://github.com/stein155/retouch/discussions
    about: For setup help and general questions (enable Discussions in repo settings to use this).
